### PR TITLE
Feature proposal: generate html

### PR DESCRIPTION
**Pull request by antlio**
Hey @michaelkofron, thank again for that gem 🙌 .

Here what this PR does:
1. Adds  a `#generate_html` method
2. Refacto common methods between string & html generation
3. Updates bin file file with newly introduce format

As I used your gem for a project, I was looking to display ASCII format in an HTML page from an image, and found myself limited by the string generation that would not be colored. I updated then the code to be able to do so. Do not feel obligated to add it to the gem, but I just wanted to share the update in case it could be valuable to someone else.

Looking forward to have your feedback on it!

### CODE REVIEW

**Comment by ronald2wing** [comment]
Can somebody merge this PR? This is very useful! Or can you create a new Git repo instead?

**Comment by antlio** [comment]
hey @ronald2wing thanks for the feedback! i'll fork it up including that change and hit you up

**Comment by ronald2wing** [comment]
> hey @ronald2wing thanks for the feedback! i'll fork it up including that change and hit you up

Thank you for your quick response. Also, I don't see the color working when I am using this gem on Rails. I wonder if the HTML will have color or not.

Thank you again for working on this gem.

**Comment by antlio** [comment]
Yes it should be colored, i'll give a look there asap and share what i used on my side!

**Comment by ronald2wing** [comment]
Amazing

**Comment by ronald2wing** [comment]
@antlio I am getting
`undefined local variable or method `as_string' for an instance of Image2ASCII`
Do you have any idea why I am getting this error?
Also, please update [image2ascii.gemspec](https://github.com/michaelkofron/image2ascii/blob/main/image2ascii.gemspec) for a newer version.

Thank you again for your contribution.

**Comment by antlio** [comment]
[here what i used](https://raw.githubusercontent.com/Grinta/og/main/lib/image2ascii.rb?token=GHSAT0AAAAAAB4SSPIX6ASQAPMAMUI2LXL2ZTL5MVA) finally in my project in order to generate ascii for og image from an image uri.

do you have an example of how you are using the gem?

**Comment by ronald2wing** [comment]
@antlio 
I can't view your link. I see a token query in the link. Is it a private link?
```
    ascii_content = Image2ASCII.new(ActiveStorage::Blob.service.path_for(ascii_image.ascii_art.temp_image.key))
    ascii_image.content = ascii_content.generate
```
My code is very basic. It gets the image from ActiveStorage and runs generate. It worked with the older version but failed with the new code. I have added the format 'html', but it does not work either.

**Comment by antlio** [comment]
oh yes my bad!

i'm using it like this (which is different that your case)

```ruby
def ascii_html
  if params[:logo_url]
    ascii = Image2ASCII.new(params[:logo_url])
    ascii.chars = " % ( # "
    ascii.generate_html(width: 140)
  else
    File.read("public/images/placeholder-outline.html")
  end
end

**Comment by ronald2wing** [comment]
Can you send me the logo URL you are using for testing?
Also, this is what I am using in my Gemfile:
`gem "image2ascii", branch: "main", git: "https://github.com/michaelkofron/image2ascii.git"
`

**Comment by ronald2wing** [comment]
If I use generate_html, I will get:
`private method `generate_html' called for an instance of Image2ASCII
`

**Comment by antlio** [comment]
oh right cause i've implemented it differently. i think you should access it through `args[:format] == :html`, so you should pass it the html format

**Comment by antlio** [comment]
like `ascii.generate(format: :html)`

**Comment by ronald2wing** [comment]
I will get
`undefined local variable or method 'as_string' for an instance of Image2ASCII`
if I use generate(format: 'html')

**Comment by ronald2wing** [comment]
Hello, I did use `ascii.generate(format: :html)` in the beginning. It does not work. Can you install the gem and try again? Both `generate_html` and `generate` don't work. `generate` will give an `undefined local variable or method 'as_string' for an instance of Image2ASCII` error.

**Comment by michaelkofron** [comment]
Yeah from a quick quick glance I see the shovel operator << inside
generate_string is referencing a non-set variable “as_string”. I think you
should replace “as_string” with “ascii_string” and pull request it as a fix.

Thanks!

**Comment by ronald2wing** [comment]
Let me try today. @michaelkofron Are you going to update the Gemfile info to make sure it will use the newer version?

**Comment by ronald2wing** [comment]
I don't see colors in the HTML.
I am using 
image.
Is there some formatting requirement to see colors in the generated ASCII?

**Pull request merged**
